## Diferencia entre ndarray y matrix en Numpy:

Si bien son similares y puede ser utilizadas ambas como una matriz, la diferencia principal entre ellas es que numpy.mat únicamente acepta estructuras bidimensionales, mientras que ndarray permite utilizar estructuras N dimensionales.

A continuación un ejemplo de un ndarray y matriz de 2 dimensiones, 3x3.

In [102]:
import numpy as np
a = np.arange(9).reshape(3,3)
b = np.matrix('1 2 3; 4 5 6; 7 8 9')
print("ndarray: \n",a,"\n")
print("matriz: ")
print(b)

ndarray: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

matriz: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


A continuación se muestra un ejemplo de ndarray de 3 dimensiones, 3x3x3.  Algo que no es posible realizar con matrices:

In [63]:
a = np.arange(27).reshape(3,3,3)
print("ndarray de 3x3x3:\n", a)

ndarray de 3x3x3:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Otra diferencia que existe entre ambos es que si se tiene 2 matrices a y b, el resultado de a x b será la multiplicación de matrices, por el contrario si se tienen 2 ndarray y se realiza a x b, el resultado será un ndarray de las mismas dimensiones con el producto de cada uno de los elementos posición por posición.  A continuación un ejemplo:

In [101]:
a = np.arange(9).reshape(3,3)
print("Siendo a: \n",a)
print("\nSe muestra a continuación el resultado de a x a:")
print("\n- Con ndarrays: \n",a*a)
a=np.matrix('0 1 2; 3 4 5; 6 7 8')
print("\n- Con matrices: \n",a*a)

Siendo a: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Se muestra a continuación el resultado de a x a:

- Con ndarrays: 
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

- Con matrices: 
 [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


Ambos, matrix y ndarray poseen la capacidad de retornar la transpuesta con .T, sin embargo, solo con matrices puede retornarse la matriz inversa.

In [103]:
a=np.matrix('0 1 2; 3 4 5; 6 7 8')
print("Matriz original: \n", a)
print("\nMatriz transpuesta: \n", a.T)
print("\nMatriz transpuesta: \n", a.H)

Matriz original: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Matriz transpuesta: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

Matriz transpuesta: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


# Referencias

https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u

https://docs.scipy.org/doc/numpy/user/quickstart.html

https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html

