In [6]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

Para 1 variable y grado 1

In [15]:
X = np.arange(1).reshape(1, 1)
X
poly = PolynomialFeatures(1)
poly.fit_transform(X)

array([[1., 0.]])

Para 2 variables y grado 2

In [9]:
X = np.arange(2).reshape(1, 2)
X
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[1., 0., 1., 0., 0., 1.]])

Para 2 variables y grado 3

In [10]:
X = np.arange(2).reshape(1, 2)
X
poly = PolynomialFeatures(3)
poly.fit_transform(X)

array([[1., 0., 1., 0., 0., 1., 0., 0., 0., 1.]])

Para 3 variables y grado 1

In [12]:
X = np.arange(3).reshape(1, 3)
X
poly = PolynomialFeatures(1)
poly.fit_transform(X)

array([[1., 0., 1., 2.]])

Para 3 variables y grado 2

In [13]:
X = np.arange(3).reshape(1, 3)
X
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[1., 0., 1., 2., 0., 0., 0., 1., 2., 4.]])

Para 3 variables y grado 3

In [14]:
X = np.arange(3).reshape(1, 3)
X
poly = PolynomialFeatures(3)
poly.fit_transform(X)

array([[1., 0., 1., 2., 0., 0., 0., 1., 2., 4., 0., 0., 0., 0., 0., 0.,
        1., 2., 4., 8.]])

Para 5 variables, grado 5  (exagerando un poco la cantidad)

In [18]:
X = np.arange(5).reshape(1, 5)
X
poly = PolynomialFeatures(5)
poly.fit_transform(X)

array([[1.000e+00, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        2.000e+00, 3.000e+00, 4.000e+00, 4.000e+00, 6.000e+00, 8.000e+00,
        9.000e+00, 1.200e+01, 1.600e+01, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 4.000e+00, 6.000e+00,
        8.000e+00, 9.000e+00, 1.200e+01, 1.600e+01, 8.000e+00, 1.200e+01,
        1.600e+01, 1.800e+01, 2.400e+01, 3.200e+01, 2.700e+01, 3.600e+01,
        4.800e+01, 6.400e+01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+0

Podemos ver que requiere un número exagerado de combinaciones dentro del polinomio, lo cuál hará que el modelo sea mucho más lento

### **Conclusiones:**

Se observó que mientras más se incrementa el número de variables y grado de polinomio, el volumen espacial crece exponencialmente, lo cual perjudica a trabajar con estos polinomios, ya que así como crece el volumen espacial, de igual forma se necesita que crezca la cantidad de datos.  Cuantas más combinaciones de variables dentro del polinomio mayor probabilidad de tener información redundante existe, lo cual es perjudicial cuando se trabaja con modelos de predicción.  Entre mayor sea el número de características en un polinomio, mayor será el tiempo de procesamiento que tomará su análisis computacional.